### 정규 표현식 사용해보기

- 전화번호만 찾기

In [2]:
# 전화번호를 찾는 정규표현식 0\d{1,2}[ -]?\d{3,4}[ -]?\d{3,4}를 빈칸에 입력하세요.
regex = r'0\d{1,2}[ -]?\d{3,4}[ -]?\d{3,4}'  

# 주소록입니다. 이후 강의에서 모두 이 search_target을 사용합니다.
search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

02-123-4567
070-9999-9999
010 2454 3457


### 숫자 대표 문자

- \d는 숫자를 대표하는 정규표현식입니다. 이때 d는 digit을 뜻합니다.

In [3]:
regex = r'\d'

# 주소록입니다. 이후 강의에서 모두 이 search_target을 사용합니다.
search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

0
2
1
2
3
4
5
6
7
0
7
0
9
9
9
9
9
9
9
9
0
1
0
2
4
5
4
3
4
5
7


### 글자 대표 문자

- \w는 글자를 대표하는 정규표현식입니다.
- a, b, c, 가, 나, 다, 1, 2와 같은 문자와 숫자를 포함합니다.
- 특수문자는 포함하지 않지만, _(언더스코어)는 포함합니다.

In [4]:
# 빈칸에 정규표현식을 적습니다.
regex = r'\w'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

L
u
k
e
S
k
y
w
a
r
k
e
r
0
2
1
2
3
4
5
6
7
l
u
k
e
d
a
u
m
n
e
t
다
스
베
이
더
0
7
0
9
9
9
9
9
9
9
9
d
a
r
t
h
_
v
a
d
e
r
g
m
a
i
l
c
o
m
p
r
i
n
c
e
s
s
l
e
i
a
0
1
0
2
4
5
4
3
4
5
7
l
e
i
a
g
m
a
i
l
c
o
m


### 하나 이상

- \d는 숫자를 한글자만 찾습니다. 그런데, 전화번호를 구성하는 043이나 2568같이 연결된 숫자를 찾고 싶을 때는 어떻게 해야 할까요?
- 그럴 땐 +를 이용하면 됩니다. +는 "하나 혹은 그 이상 연결된"이라는 뜻입니다. 따라서 \d+는 "하나 혹은 그 이상 연결된 숫자"를 의미합니다.

In [5]:
# 빈칸에 정규표현식을 적습니다.
regex = r'\d+'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['02', '123', '4567', '070', '9999', '9999', '010', '2454', '3457']


### 0개 이상

- 정규표현식으로 010, 123, 456 중 자연수를 찾으려면 어떻게 해야 할까요? 
- 자연수는 0으로 시작하지 않으니 자연수의 첫자리는 반드시 1 ~ 9 중에 하나이어야 합니다.
- 그다음 자리부터는 0~9 사이의 숫자가 나올 수도 있고, 나오지 않을 수도 있지요. 다시 말해, 자연수는 다음과 같이 표현할 수 있습니다.
1. 처음에 1~9중 하나의 숫자가 나온 다음 
2. 그 뒤에는 숫자가 0개 이상 나오면 
- *은 "0개 이상"이라는 뜻입니다. 따라서 \d*는 "숫자가 0개 이상이다"를 의미합니다. 이를 이용하면 자연수는 [1-9]\d*로 표현할 수 있습니다.

In [6]:
regex = r'[1-9]\d*'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

2
123
4567
70
9999
9999
10
2454
3457


### 있거나 없거나 (1)

- 전화번호는 "-"을 포함하거나, 포함하지 않을 수 있습니다. 예를 들어, 다음은 모두 유효한 전화번호입니다.
```021234567
02-123-4567
```
- 따라서 전화번호는 연속되는 숫자 3 ~ 4개 사이에 -가 있거나 없다고 표현할 수 있습니다.
- ?는 '있거나 없거나'라는 뜻입니다. 따라서 -?는 "-가 있거나 없다"를 의미합니다. 따라서 이를 연속하는 숫자는 \d+와 조합하면 전화번호를 찾는 정규표현식을 만들 수 있습니다.
- \d+-?\d+-?\d+

In [7]:
regex = r'\d+-?\d+-?\d+'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['02-123-4567', '070-9999-9999', '010', '2454', '3457']


### 있거나 없거나 (2)

\d+-?\d+-?\d+ 정규표현식은 한계가 있습니다. "010 2454 3457"과 같이 공백이 포함된 전화번호를 찾을 수 없지요.
```
021234567
02-123-4567
010 2454 3457
```
모든 전화번호를 찾으려면 

"-가 있거나 없다"는 조건이 아니라
"- 또는 공백이 있거나 없다"는 조건을 써야 합니다.
- 또는 (공백)이 있거나 없다는 조건은 [- ]?로 표현할 수 있습니다.

In [9]:
regex = r'\d+[- ]?\d+[- ]?\d+'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['02-123-4567', '070-9999-9999', '010 2454 3457']


### n번 (1)
- 앞서 배운 \d+[- ]?\d+[- ]?\d+ 정규표현식으로는 전화번호를 찾는데 한계가 있습니다. 
- "0030589-5-95826"과 같이 연결된 숫자가 너무 많은 문자열도 전화번호라고 인식합니다.

In [10]:
# 본 문제는 실행만하면 통과하는 문제입니다.
regex = r'\d+[- ]?\d+[- ]?\d+'

search_target = '''이상한 전화번호 0030589-5-95826
Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['0030589-5-95826', '02-123-4567', '070-9999-9999', '010 2454 3457']


### n번 (2)
- {숫자}는 "숫자번 반복한다"는 뜻입니다. 예를 들어 \d{2}는 "숫자가 연속 두 번 나온다"는 뜻입니다.

In [11]:
regex = r'\d{2}[- ]?\d{3}[- ]?\d{4}'

search_target = '''이상한 전화번호 0030589-5-95826
Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['02-123-4567']


### n ~ m 번

- 앞서 배운 \d{2}[- ]?\d{3}[- ]?\d{4} 정규표현식으로는 전화번호를 찾는데 한계가 있습니다. 전화번호의 첫 부분에 숫자가 3번(010 2454 3457) 나오는 경우를 인식하지 못하지요.
```
021234567
02-123-4567
010 2454 3457
```
- {숫자1, 숫자2}는 "숫자1부터 숫자2까지 반복한다"는 뜻입니다. 예를 들어, \w{2,3}는 "문자가 2 ~ 3번 나온다"는 뜻입니다.
- 전화번호의 자릿수는 다음과 같습니다. 따라서 전화번호는 \d{2,3}[- ]?\d{3,4}[- ]?\d{4}와 같이 표현할 수 있습니다.

In [12]:
regex = r'\d{2,3}[- ]?\d{3,4}[- ]?\d{4}'

search_target = '''이상한 전화번호 0030589-5-95826
Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

#아래 부분은 본 강의에서 다루지 않습니다.
import re
result=re.findall(regex,search_target)
print(result)

['02-123-4567', '070-9999-9999', '010 2454 3457']


### 몇 개 중에 고르기
- 알파벳 중에 소문자 모음(a,e,i,o,u)만 고르고 싶을 땐 어떻게 할까요?
- 그럴 때는 [aeiou]라고 적어주세요. 정규표현식에서 대괄호[ ] 안에 글자를 넣으면 해당 글자를 모두 선택할 수 있습니다.

In [13]:
regex = r'[aeiou]'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

u
e
a
e
u
e
a
u
e
a
a
e
a
i
o
i
e
e
i
a
e
i
a
a
i
o


### 범위에서 고르기(1)

- 소문자 알파벳만 고르고 싶을 땐 어떻게 할까요? [abcdefghijklmnopqrlstuvwxyz]처럼 대괄호 안에 소문자를 모두 나열할 수도 있지만 뭔가 찜찜하지요.
- 우리는 간단히 [a-z]를 쓰도록 합시다. [a-z]는 "a부터 z까지 글자를 모두 선택하라"는 의미입니다.

In [15]:
regex = r'[a-z]'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

u
k
e
k
y
w
a
r
k
e
r
l
u
k
e
d
a
u
m
n
e
t
d
a
r
t
h
v
a
d
e
r
g
m
a
i
l
c
o
m
p
r
i
n
c
e
s
s
l
e
i
a
l
e
i
a
g
m
a
i
l
c
o
m


### 범위에서 고르기 (2)

- 연속된 영어 소문자를 찾으려면 어떻게 할까요?
- 소문자를 뜻하는 [a-z]와
- 반복을 뜻하는 +를 붙여 => [a-z]+를 씁니다.

In [22]:
regex = r'[a-z]+'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

uke
kywarker
luke
daum
net
darth
vader
gmail
com
princess
leia
leia
gmail
com


### 한글 고르기
- 한글의 첫 번째 글자는 가이고 마지막 글자는 힣입니다. 따라서 한글은 [가-힣]으로 찾을 수 있습니다.
- 단, 이 방식으로는 ㄱㄴㄷ이나 ㅏㅑㅓㅕ같은 낱글자는 찾을 수 없습니다. 

In [23]:
regex = r'[가-힣]+'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

다스베이더


### 기타 대표문자

- 숫자(\d)나 글자(\w)이외에도 다양한 대표 문자가 있습니다.
- 빈칸에 다양한 대표 문자를 입력해서 결과를 확인해 보세요.

- \s 공백 문자(스페이스, 탭, 뉴라인)
- \S 공백 문자를 제외한 문자
- \D 숫자를 제외한 문자
- \W 글자 대표 문자를 제외한 글자들(특수문자, 공백 등)

In [25]:
regex = r'\W'

search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
다스베이더 070-9999-9999 darth_vader@gmail.com
princess leia 010 2454 3457 leia@gmail.com'''

# 정규표현식과 일치하는 부분을 모두 찾아주는 파이썬 코드입니다.
import re
result = re.findall(regex, search_target)
print("\n".join(result))

 
 
-
-
 
@
.


 
-
-
 
@
.


 
 
 
 
 
@
.
